[package]
name = "jack_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jack_platform = { path = "../jack_platform" }
wasm-bindgen = "0.2.91"

[dependencies.web-sys]
version = "0.3.68"
features = ["console"]
